Use System.Logger for logging.
./gradlew :example:systemTest failed after ~10 runs, 2 runs, and then 227 runs. This seems unlikely to be caused by logging changes. It seems more likely that was a latent race condition associated with the robot code closing while the controller is still running the simulating. In particular, I am occasionally seeing DeepBlueSim exit with the following error:

java.lang.RuntimeException: Exception while waiting for simulation to be done
        at DeepBlueSim.main(DeepBlueSim.java:401)
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:628)
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:605)
        at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:410)
        at org.team199.wpiws.connection.ConnectionProcessor.lambda$broadcastMessage$5(ConnectionProcessor.java:146)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.team199.wpiws.connection.ConnectionProcessor.broadcastMessage(ConnectionProcessor.java:146)
        at org.team199.wpiws.connection.ConnectionProcessor.broadcastMessage(ConnectionProcessor.java:138)
        at org.team199.wpiws.connection.ConnectionProcessor.broadcastMessage(ConnectionProcessor.java:121)
        at org.team199.wpiws.devices.SimDeviceSim.set(SimDeviceSim.java:162)
        at org.team199.wpiws.devices.SimDeviceSim.set(SimDeviceSim.java:59)
        at org.team199.deepbluesim.mediators.GyroMediator.run(GyroMediator.java:43)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at org.team199.deepbluesim.Simulation.runPeriodicMethods(Simulation.java:65)
        at DeepBlueSim.main(DeepBlueSim.java:385)
Error: Connection Refused! Trying again in 0 second(s)
local: /127.0.0.1:54344 remote: localhost/127.0.0.1:3300 disconnected by remote host (1006):
Reconnecting...
local: <unknown> remote: <disconnected> disconnected by local host (-1): Connection refused
WARNING: 'DeepBlueSim' controller exited with status: 1.